#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &
autorandr --load default &
xrdb -merge ~/.Xresources &
pipewire &
mpd &
picom &
/usr/lib/xfce4/notifyd/xfce4-notifyd &
udiskie &
/home/mafuyu/.config/polybar/./launch.sh &
nitrogen --restore &
xclip &

bspc monitor HDMI1 -d I II III IV V VI VII

bspc config border_width         2
bspc config window_gap          5

bspc config normal_border_color a36098
bspc config focused_border_color ffa3f0
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config focus_follows_pointer true
